- name: check if user is in subuid file
  lineinfile:
    path: /etc/subuid
    regexp: '^{{ container_run_as_user }}:.*$'
    state: absent
  check_mode: yes
  register: uid_line
  changed_when: false
  when: container_run_as_user != 'root'

- name: check if group is in subgid file
  lineinfile:
    path: /etc/subgid
    regexp: '^{{ container_run_as_group }}:.*$'
    state: absent
  check_mode: yes
  register: gid_line
  changed_when: false
  when: container_run_as_group != 'root'

- name: ensure user is in subuid file, if it was missing
  lineinfile:
    path: /etc/subuid
    regexp: "^{{ container_run_as_user }}:.*"
    line: "{{ container_run_as_user }}:165536:65536"
    create: yes
    mode: '0644'
    owner: root
    group: root
  when: not uid_line.found and container_run_as_user != 'root'

- name: ensure group is in subgid file, if it was missing
  lineinfile:
    path: /etc/subgid
    regexp: "^{{ container_run_as_group }}:.*"
    line: "{{ container_run_as_group }}:165536:65536"
    create: yes
    mode: '0644'
    owner: root
    group: root
  when: not gid_line.found and container_run_as_group != 'root'


