---

- name: reload systemctl
  systemd:
    daemon_reload: true

- name: start service
  systemd:
    name: "{{ service_name }}"
    state: started

- name: restart service
  systemd:
    name: "{{ service_name }}"
    state: restarted
